[rewrite_local]
# Token捕获规则
^https:\/\/api\.alldragon\.com\/mkt2\/ url script-response-body dragon_all_in_one.js

[task_local]
# 每日签到任务
0 9 * * * dragon_all_in_one.js, tag=龙腾签到, img-url=airplane.circle.fill, enabled=true

[mitm]
hostname = api.alldragon.com
